assets:
  sources:
    - _assets/stylesheets
    - _assets/javascripts
    - _assets/images
    - _vendor/symbolset
  precompile:
    - application.css
    - ^ss
    - .png|.jpg|.jpeg|.gif
    - application.js

